# Generated by Django 4.1.4 on 2024-09-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField()),
                ('Temperature_Max', models.CharField(max_length=5)),
                ('Temperature_Min', models.CharField(max_length=5)),
                ('Humidity_Max', models.CharField(max_length=5)),
                ('Humidity_Min', models.CharField(max_length=5)),
                ('PH_Max', models.CharField(max_length=5)),
                ('PH_Min', models.CharField(max_length=5)),
                ('EC_Max', models.CharField(max_length=5)),
                ('EC_Min', models.CharField(max_length=5)),
                ('Light_Max', models.CharField(max_length=5)),
                ('Light_Min', models.CharField(max_length=5)),
            ],
        ),
    ]
