# Generated by Django 4.1.4 on 2023-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethio_leap_gui_app', '0003_alter_controlparameters_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Relay1', models.BooleanField()),
                ('Relay2', models.BooleanField()),
                ('Relay3', models.BooleanField()),
                ('Relay4', models.BooleanField()),
                ('Relay5', models.BooleanField()),
                ('Relay6', models.BooleanField()),
                ('Relay7', models.BooleanField()),
                ('Relay8', models.BooleanField()),
            ],
        ),
    ]
