# Generated by Django 4.1.4 on 2023-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethio_leap_gui_app', '0004_relays'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutchBucketOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('FirstFeedStart', models.TimeField()),
                ('SecondFeedStart', models.TimeField()),
                ('ThirdFeedStart', models.TimeField()),
                ('FeedDuration', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DutchBucketTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('FirstFeedStart', models.TimeField()),
                ('SecondFeedStart', models.TimeField()),
                ('ThirdFeedStart', models.TimeField()),
                ('FeedDuration', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SeedlingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('FirstFeedStart', models.TimeField()),
                ('SecondFeedStart', models.TimeField()),
                ('ThirdFeedStart', models.TimeField()),
                ('FeedDuration', models.CharField(max_length=3)),
            ],
        ),
    ]
