# Generated by Django 4.1.4 on 2024-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data_app', '0005_dutchbucketone_dutchbuckettwo_seedlingcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
