# Generated by Django 4.1.4 on 2024-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethio_leap_gui_app', '0006_alter_sensorsdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='Humidity',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='Temprature',
            field=models.CharField(max_length=4),
        ),
    ]
